## Numpy

- Logon k likhy howy bary bar code

- Linear Algebra Library

 Intel MKL or OpenBLAS

- How to use
- How it looks like

In [2]:
import numpy as np
a= np.arange(6)
a2= a[np.newaxis, :]
a2.shape

(1, 6)

In [4]:
a=np.array([5,5,5,5,5])
a

array([5, 5, 5, 5, 5])

In [5]:
type(a)

numpy.ndarray

In [8]:
#list of list
b= np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# Vector & Matrix


# 1-D array

In [10]:
a=np.array([5,5,5,])
a

array([5, 5, 5])

In [11]:
type(a)

numpy.ndarray

In [12]:
len(a)

3

In [13]:
a[0]

5

In [14]:
a[0:]

array([5, 5, 5])

In [36]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [37]:
b=np.zeros(2)
b

array([0., 0.])

In [39]:
c=np.ones(3)
c

array([1., 1., 1.])

In [44]:
d=np.empty(3)
d

array([1., 1., 1.])

In [47]:
# with range of elements
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [48]:
# with specific range of elements
f= np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [56]:
# continue
g=np.arange(1,20,3)
g

array([ 1,  4,  7, 10, 13, 16, 19])

In [60]:
# linerly spaced arrays
h=np.linspace(2,2,num=10)
h

array([2.        , 1.77777778, 1.55555556, 1.33333333, 1.11111111,
       0.88888889, 0.66666667, 0.44444444, 0.22222222, 0.        ])

# 2-D array

In [18]:
b= np.array([[5,5,5],[6,6,6],[7,7,7]])
b

array([[5, 5, 5],
       [6, 6, 6],
       [7, 7, 7]])

In [16]:
len(b)

3

In [20]:
b[1]

array([6, 6, 6])

In [21]:
b[0:]

array([[5, 5, 5],
       [6, 6, 6],
       [7, 7, 7]])

# 3-D array