# numpy practice session

In [1]:
import numpy as np


In [2]:
# Creating an array using numpy

In [3]:
# 1D-array
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [4]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(price)

3

In [8]:
len(food)

3

In [9]:
price[2]

5

In [10]:
price[0:]

array([5, 5, 5])

In [11]:
food[1]

'Samosa'

In [12]:
price.mean()

5.0

In [13]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
# ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [23]:
# empty 
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [24]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [28]:
#line space
np.linspace(0,100, num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [30]:
#specify your data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [31]:
#specify your data type
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

# Array function

In [33]:
a= np.array([10,15,19,123,52,23,2.8,5.9,4.6])
a

array([ 10. ,  15. ,  19. , 123. ,  52. ,  23. ,   2.8,   5.9,   4.6])

In [36]:
a.sort()
a

array([  2.8,   4.6,   5.9,  10. ,  15. ,  19. ,  23. ,  52. , 123. ])

In [37]:
b=np.array([10.8,5.9,4.3,3.9,4.9,8.9])
b

array([10.8,  5.9,  4.3,  3.9,  4.9,  8.9])

In [40]:
c = np.concatenate((a,b))
c

array([  2.8,   4.6,   5.9,  10. ,  15. ,  19. ,  23. ,  52. , 123. ,
        10.8,   5.9,   4.3,   3.9,   4.9,   8.9])

In [41]:
c.sort()
c

array([  2.8,   3.9,   4.3,   4.6,   4.9,   5.9,   5.9,   8.9,  10. ,
        10.8,  15. ,  19. ,  23. ,  52. , 123. ])

# 2-D array

In [42]:
a = np.array([[1,2,2,3,6],[5,4,6,3,9]])
a

array([[1, 2, 2, 3, 6],
       [5, 4, 6, 3, 9]])

In [43]:
b = np.array([[8,7,6,5,4],[5,4,3,2,1]])
b

array([[8, 7, 6, 5, 4],
       [5, 4, 3, 2, 1]])

In [45]:
c = np.concatenate((a,b))
c

array([[1, 2, 2, 3, 6],
       [5, 4, 6, 3, 9],
       [8, 7, 6, 5, 4],
       [5, 4, 3, 2, 1]])

In [50]:
c= np.concatenate((a,b), axis=0)
c

array([[1, 2, 2, 3, 6],
       [5, 4, 6, 3, 9],
       [8, 7, 6, 5, 4],
       [5, 4, 3, 2, 1]])

In [57]:
a= np.array ([[[0,1,2,3,4],[5,6,7,8,9]],[[0,1,2,3,4],[5,6,7,8,9]],[[0,1,2,3,4],[5,6,7,8,9]]])
a

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [58]:
# to find the number of dimensions
a.ndim

3

In [59]:
b= np.array([[5,6,7],[8,9,10],[10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [61]:
b.ndim

2

In [62]:
# size (number of elements)
a.size

30

In [64]:
#shape
a.shape

(3, 2, 5)

In [67]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
# RESHAPE
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
# convert 1D into 2 D
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
a.shape

(9,)